PlebNetDev_Meeting_Notes_Jul2023
plebnet-dev/meeting-notes pull request #1
Opened 2023-07-31 01:19 UTC by Bitc0indad

PlebNet Dev Monthly Meetup in July 

Meeting Minutes attached for review @eriknewland  & @bitkarrot  please add when I missed specifics thanks!

2023-07-31 01:43 UTC, bitkarrot requested changes
please see corrections requested. Thanks for posting!

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +1. Continue working on NOSTR Projects (Spellkit, NOSTR accounts, NIP\*05, and front-end application). (ErikNewland)
nostrkit, not spell kit

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- Progress on spellkit template outline.
nostr kit not spell kit

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- NIP\*05 issues: Python attempt to vanity npub (RONNA).
Rana not RONNA

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- Get an aldy account with lnurl.
getalby.com not aldy

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- NOSTR Telegram Bridge for public messaging and encouraging NOSTR adoption.
bloggingbitcoin is working on these nostr bridges

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- Integration of ASTRO template for automatic NOSTR posting when a .md blog post is created.
the astro-nostr project is an open for anyone interested in working on something independently

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- No public instance?
for now, no public testnet. members only

2023-07-31 01:43 UTC, bitkarrot commented on PlebNetDev_Meeting_Notes_Jul2023.md
> +- More unit tests and modules for LNBits, aiming for release in August.
Please edit this line to say the following: 

The pylnbits sdk release will be in august. If anyone is interested in writing docs or helping with unit testing, this is a also a good first project to work on.

2023-07-31 03:20 UTC, Bitc0indad commented
@bitkarrot Feedback updated. @eriknewland  any updates please comment

2023-08-01 21:04 UTC, bitkarrot commented
@Bitc0indad looks fine to me, approved. @eriknewland  for the final confirm and merge please

2023-08-03 00:32 UTC, eriknewland approved these changes
looks good!

2023-08-03 00:32 UTC, merged