November 2023 Meeting Minutes PR
plebnet-dev/meeting-notes pull request #4
Opened 2023-11-22 05:41 UTC by surfersol

Please note that PlebNetDev_Meeting_Notes_Oct2023.md has a description of "November 2023 Meeting Minutes" and should be "October 2023 Meeting Minutes"

2023-11-22 22:26 UTC, bliotti commented
@surfersol do you need me to resolve the conflicts?

2023-11-22 22:34 UTC, bliotti commented
Assuming I am cool to merge? Does the website just reference this repo's md files now?

2023-11-23 00:40 UTC, surfersol commented
> Question - Assuming I am cool to merge?   Answer - yes if all well.

Question -Does the website just reference this repo's md files now? 
Answer - repo's md is not in the website of November blog as this PR needs to be approved and then I can put this November meeting minute's website to the the November blog.

Question - I don't see any pipeline stuff for this repo.
Answer - Unsure in how to answer or create a pipeline stuff for this repo.  Do you have to approve and merge to the main website?

2023-11-23 05:46 UTC, bliotti commented on PlebNetDev_Meeting_Notes_Nov2023.md
> +[Nostr mail](https://github.com/asherp/nostr-mail/tree/app) in association with [kivyMD](https://github.com/kivymd/KivyMD/blob/master/README.md)
make all these bullet points

2023-11-23 05:47 UTC, bliotti requested changes

2023-11-23 05:47 UTC, bliotti commented on PlebNetDev_Meeting_Notes_Nov2023.md
> +    Prospect Workshops
remove indention

2023-11-23 05:47 UTC, bliotti commented on PlebNetDev_Meeting_Notes_Nov2023.md
> +#### 7.	Other Discussion Points
make bullet points

2023-11-23 05:47 UTC, bliotti commented on PlebNetDev_Meeting_Notes_Nov2023.md
> +#### 9/  Previous Meeting Minutes (https://github.com/plebnet-dev/meeting-notes)
fix slash

2023-11-23 05:47 UTC, bliotti commented on PlebNetDev_Meeting_Notes_Nov2023.md
> +- Designing your apps with [KivyMD]((https://github.com/kivymd/KivyMD/blob/master/README.md) by (@Asherp)[https://github.com/asherp]
fix

2023-11-23 06:41 UTC, merged